# Generated by Django 3.0.3 on 2020-05-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='website',
            new_name='band_image_url',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='name',
            new_name='instrument_name',
        ),
    ]
