# Generated by Django 3.0.3 on 2020-05-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0005_auto_20200507_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(default='Current', max_length=15),
        ),
    ]
