# Generated by Django 3.0.3 on 2020-05-09 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0007_song_music_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='musician_id',
        ),
        migrations.AddField(
            model_name='role',
            name='member_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bandapp.Member'),
        ),
    ]
