# Generated by Django 3.0.3 on 2020-05-09 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0008_auto_20200509_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='role_id',
        ),
        migrations.AddField(
            model_name='album',
            name='role_id',
            field=models.ManyToManyField(default=1, to='bandapp.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandapp.Member'),
        ),
    ]
