# Generated by Django 3.0.3 on 2020-05-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0010_auto_20200509_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='band',
            name='band_image_url',
            field=models.URLField(default='https://images.pexels.com/photos/375893/pexels-photo-375893.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'),
        ),
        migrations.AlterField(
            model_name='song',
            name='music_video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=Q4SxizAg6bk'),
        ),
    ]
