# Generated by Django 3.0.3 on 2020-05-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0011_auto_20200509_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='band_id',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='band_id',
            new_name='band',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='musician_id',
            new_name='musician',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='instrument_id',
            new_name='instrument',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='member_id',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='album_id',
            new_name='album',
        ),
    ]
