# Generated by Django 3.0.3 on 2020-05-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0012_auto_20200509_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='role',
            field=models.ManyToManyField(blank=True, to='bandapp.Role'),
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almbum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandapp.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandapp.Role')),
            ],
        ),
    ]
