# Generated by Django 3.0.3 on 2020-05-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0013_auto_20200513_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='role',
            name='member',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='almbum',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='album',
            name='role',
        ),
        migrations.AddField(
            model_name='album',
            name='musician',
            field=models.ManyToManyField(to='bandapp.Musician'),
        ),
        migrations.AddField(
            model_name='musician',
            name='band',
            field=models.ManyToManyField(to='bandapp.Band'),
        ),
        migrations.AddField(
            model_name='musician',
            name='instrument',
            field=models.ManyToManyField(to='bandapp.Instrument'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
