# Generated by Django 3.0.3 on 2020-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0014_auto_20200513_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['instrument_name']},
        ),
        migrations.AlterModelOptions(
            name='musician',
            options={'ordering': ['full_name']},
        ),
        migrations.AddField(
            model_name='instrument',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='musician',
            field=models.ManyToManyField(blank=True, to='bandapp.Musician'),
        ),
        migrations.AlterField(
            model_name='band',
            name='band_image_url',
            field=models.URLField(default='https://bit.ly/2xZwci2'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='band',
            field=models.ManyToManyField(blank=True, to='bandapp.Band'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument',
            field=models.ManyToManyField(blank=True, to='bandapp.Instrument'),
        ),
    ]
