# Generated by Django 3.0.3 on 2020-05-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0016_auto_20200514_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
