# Generated by Django 3.0.3 on 2020-05-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0002_auto_20200507_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='last_name',
        ),
        migrations.AddField(
            model_name='musician',
            name='full_name',
            field=models.CharField(default=None, max_length=70),
            preserve_default=False,
        ),
    ]
