# Generated by Django 3.0.3 on 2020-05-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0003_auto_20200507_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Instrument_id',
            new_name='instrument_id',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='band_id',
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandapp.Band')),
                ('musician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bandapp.Musician')),
            ],
        ),
    ]
