# Generated by Django 3.0.3 on 2020-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0006_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music_video_url',
            field=models.URLField(default='http://www.none.com'),
            preserve_default=False,
        ),
    ]
