# Generated by Django 3.0.3 on 2020-05-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0009_auto_20200509_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='role_id',
            field=models.ManyToManyField(to='bandapp.Role'),
        ),
        migrations.AlterField(
            model_name='song',
            name='music_video_url',
            field=models.URLField(default=''),
        ),
    ]
